language: java
dist: trusty
jdk:
  - openjdk8
  - oraclejdk8
  - openjdk9
  - oraclejdk9
  - openjdk11
  - oraclejdk11
  - openjdk12
  - oraclejdk12
install: true
script:
  - mvn clean install
after_success:
  - mvn clean test jacoco:report coveralls:report